### PR TITLE
Water.java added and updated

### PR DESCRIPTION
**Pull request by IrodaRustamiy**
Please review and approve

### CODE REVIEW

**Comment by olenakorenchuk** [comment]
Good job Iroda!

**Review by soviet95 — COMMENTED** [review]
good job

**Review by olenakorenchuk — COMMENTED** [review]
Good Job Iroda!

**Review by tatianaleonard — APPROVED** [review]

**Review by soviet95 — APPROVED** [review]

**Review by olenakorenchuk — APPROVED** [review]

**Comment by IrodaRustamiy** [comment]
Thank you team, you are the best!

**Pull request merged**
